services:
  server:
   build: .
   restart: always
   ports:
    - "8080:8080"
   depends_on:
    - mysqldb
  mysqldb:
   image: mysql:8.0.29
   restart: always
   ports:
    - "3307:3306"
   environment:  # Corrected the typo here
    MYSQL_ROOT_PASSWORD: DbUser@123
    MYSQL_DATABASE: course-api
    MYSQL_USER: dbuser
    MYSQL_PASSWORD: DbUser@123